package capitalOne.Qa.Test.OpenAccount;

import java.util.ArrayList;
import java.util.Iterator;

import org.testng.annotations.DataProvider;

import capitalOneBank.QA.Base.BaseClass;

public class OpenAccountTestDataProviderClass extends BaseClass {
@DataProvider(name = "openAccountData")
public Iterator<OpenAccountTest> openAccountData(){
<OpenAccountTest> list= new ArrayList<OpenAccountTest>();
}
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
